In [21]:
import numpy as np
from sklearn import svm
from sklearn.datasets import load_iris

In [24]:
iris = load_iris()
print(iris.data)
print(iris.target)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [25]:
X=iris.data
Y=iris.target
clf = svm.LinearSVC()
clf.fit(X,Y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [29]:
predict = clf.predict([[5.1,3.5,1.4,0.5]])
predict

array([0])

In [30]:
import os

In [48]:
raw_data = './raw/'
train_data = './train/'
X = []
Y = []
for filename in os.listdir(train_data):
    filename = train_data+filename
    with open(filename,'r') as fp:
        lines = fp.readlines()
        print(len(lines))
        for idx,line in enumerate(lines):
            if idx == 0 or idx == len(lines)-1: continue
            mid = line.strip().split(',')[1:4]
            first = lines[idx-1].strip().split(',')[1:4]
            last = lines[idx+1].strip().split(',')[1:4]
            print(first)

398
['0.008602', '94.25247', '18.38117']
['0.027975', '134.2903', '52.82267']
['0.035066', '134.6431', '35.52515']
['0.002051', '70.98', '3.137741']
['0.001485', '90.2746', '1.322055']
['0.020483', '105.6293', '16.68499']
['0.057271', '135.4549', '46.48417']
['0.00352', '47.24664', '3.09747']
['0.108599', '177.3419', '91.89324']
['0.10211', '86.78719', '89.69817']
['0.003094', '82.84718', '3.18535']
['0.008709', '50.74739', '11.94905']
['0.003824', '94.28085', '3.838158']
['0.008609', '77.70632', '7.137221']
['0.00095', '164.5884', '0.915245']
['0.005268', '169.1229', '5.992291']
['0.003562', '119.281', '3.369959']
['0.068232', '14.52961', '72.84733']
['0.003466', '22.6807', '5.441493']
['0.009271', '6.833859', '6.197167']
['0.005701', '16.95279', '4.057279']
['0.059229', '56.54396', '41.45573']
['0.066501', '109.4778', '51.2996']
['0.030187', '123.7435', '52.70056']
['0.079903', '17.63067', '38.56527']
['0.013938', '96.57351', '17.6217']
['0.015353', '132.8388', '38.70233']
['0.008742

In [45]:
a=[1,2,3]
a.extend([4,5,6],[7,8,9])
a

TypeError: extend() takes exactly one argument (2 given)